config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  get 'replies/create'
  devise_for :users
  resources :tweets do
    resource :likes, only: [:create, :destroy]
    resource :replies, only: [:create]
  end
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :replies

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :likes
  has_many :like_tweets, through: :likes, source: :tweet
  has_many :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = current_user.likes.build(tweet_id: params[:tweet_id])
    like.save
    redirect_to tweets_path
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_to tweets_path
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    reply = current_user.replies.build(reply_params)
    reply.tweet_id = tweet.id
    reply.save
    redirect_to tweet_path(tweet.id)
  end

  private

  def reply_params
    params.require(:reply).permit(:body)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!, except: [:index]
    def index
      @tweets = Tweet.all
    end
  
    def show
      @tweet = Tweet.find(params[:id])
      @user = @tweet.user
      @reply = current_user.replies.build
      @replies = @tweet.replies
    end
  
    def new
      @tweet = Tweet.new
    end
  
    def create
      @tweet = Tweet.new(tweet_params)  # フォームから送られてきたデータ(body)をストロングパラメータを経由して@tweetに代入
      @tweet.user_id = current_user.id # user_idの情報はフォームからはきていないので、deviseのメソッドを使って「ログインしている自分のid」を代入
      @tweet.save
      redirect_to tweets_path
    end

    private

    def tweet_params
      #ストロングパラメーターとして、tweetModelのBodyのみを許可する
      #tweetのパラメーターはbodyとuser_idだが、user_idはツイートの投稿には不要なので許可しないようにしている
      params.require(:tweet).permit(:body)
    end
  
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
    @like_tweets = @user.like_tweets 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssociationTutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "新規投稿", new_tweet_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <%= link_to "マイページ", user_path(current_user.id) %>
    <% else %>
      <%= link_to "新規登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
      <%= link_to "ツイート一覧", tweets_path %>
      <%= link_to "ユーザー一覧", users_path %>
    <%= yield %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/replies/create.html.erb
<h1>Replies#create</h1>
<p>Find me in app/views/replies/create.html.erb</p>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/index.html.erb
<h1>Tweets#index</h1>
<p>Find me in app/views/tweets/index.html.erb</p>
<% @tweets.each do |tweet| %>
  <hr>
  <p><span>email: </span><%=link_to tweet.user.email, user_path(tweet.user.id) %></p>
  <p><span>ツイート内容: </span><%=link_to tweet.body, tweet_path(tweet.id) %></p>
  <% if user_signed_in? %>
    <% if tweet.liked_by?(current_user) %>
        <p><span>いいね: </span><%=link_to tweet.likes.count, tweet_likes_path(tweet.id), method: :delete %></p>
    <% else %>
        <p><span>いいね: </span><%=link_to tweet.likes.count, tweet_likes_path(tweet.id), method: :post %></p>
    <% end %>
  <% else %>
    <p><span>お気に入り数: </span><%= tweet.likes.count %></p>
  <% end %>
<% end %>

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>

<%= form_for @tweet do |f| %>
  <p>
    <%= f.label :body,"ツイート" %>
    <%= f.text_field :body %>
  </p>
  <%= f.submit %>
<% end %>t

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>

<p><span>email: </span><%= @user.email %></p>
<p><span>ツイート内容: </span><%= @tweet.body %></p>

<%= form_for([@tweet, @reply]) do |f| %>
  <p>
    <%= f.label :body,"コメント" %>
    <%= f.text_field :body %>
  </p>
  <%= f.submit %>
<% end %>

<% @replies.each do |reply| %>
  <hr>
  <p><span>email: </span><%=link_to reply.user.email, user_path(reply.user.id) %></p>
  <p><span>コメント内容: </span><%= reply.body %></p>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<% @users.each do |user| %>
  <hr>
  <p><span>email: </span><%=link_to user.email, user_path(user.id) %></p>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<hr>
<p><span>email: </span><%= @user.email %></p>

<% @tweets.each do |tweet| %>
  <hr>
  <p><span>ツイート内容: </span><%=link_to tweet.body, tweet_path(tweet.id) %></p>
<% end %>

<p>【いいねしたツイート】</p>
<% @like_tweets.each do |tweet| %>
  <hr>
  <p>email:<%= tweet.user.email %> <%=link_to tweet.body, tweet_path(tweet.id) %></p>
<% end %>